# Use the official Node.js image to build the React app
# We're using version 18-alpine for a lightweight image
FROM node:18-alpine AS build

# Step 2: Set the working directory  
# This is the folder inside the container where our app's files will be copied  
WORKDIR /app


# Step 3: Copy package.json and package-lock.json  
# Copying these separately allows Docker to cache dependencies  
# if they haven't changed, speeding up build times  
COPY package.json package-lock.json ./


# Step 4: Install dependencies  
# This installs all the required packages mentioned in package.json  
# using npm. If you're using yarn, replace it with "yarn install"  
RUN npm install


# Step 5: Copy the rest of the application code  
# Now, we copy all the source files to the container  
COPY . .


# Step 6: Build the React application  
# This creates an optimized production build  
# which is stored in the 'build' folder  
RUN npm run build




